package Collection.Map;

import java.util.concurrent.ConcurrentHashMap;

public class MainConcurrentHashMap {
    public static void main(String[] args) {
        //ConcurrentHashMap class IMPLEMENTS CONCURRENT MAP interface which extends MAP
        // CONCURRENCY ACHIEVE -> THREAD SAFE
        ConcurrentHashMap<Integer, String> concurrentHashMap = new ConcurrentHashMap<>();

        //internal working of ConcurrentHashMap:
        //java 7 --> SEGMENT BASED LOCKING --> 16 segments --> segment means smaller hashmaps --> map divided in 16(default) segments or 16 hashmaps
        // 16 segments has independent locking each 16 hashmap has their own lock
        // ONLY THE SEGMENT BEING WRITTEN TO OR READ FROM IS LOCKED other segment is not locked (jaha se dal re aur jo written krre wohi segment lock hoga)
        // READ: DO NOT REQUIRE LOCKING UNLESS THERE IS A WRITE OPERATION HAPPENING ON THE SAME SEGMENT
        // WRITE: LOCK the segment (put/update)

        // java8 -> NO SEGMENTATION (BCOZ 16 SEGMENTS CANNOT BE SCALED (FIX NO) IF HASHMAP TOO BIG TOO MUCH WAITING THE BIG THE HASHMAP THE BIG THE SEGMENT AND SEGMENT CAN HAVE LOT OF BUCKETS A LOT OF KEY VALUE PAIRS IN MULTIPLE SEGMENTS WE NEED TO WAIT TILL THE FIRST SEGMENT IS COMPLETED THEN SO ON)

        //It Uses --> COMPARE AND SWAP APPROACH --> no Locking EXCEPT RESIZING(0.75 TIMES 16 (capacity) = 12) OR COLLISION CASE (IN CASE OF COLLISION -LINKED LIST -->COMPLEX NOT SIMPLE VALUE CHECK IN CAS HENCE LOCK LAGANA PADTA H USS PARTICULAR BUCKET PE NA KI PURA HASHMAP PE)
        // THREAD A LAST SAW --> X = 42
        // THREAD A WORK --> MAKE X TO 50
        // CAS DOES IS-> IT CHECKS AGAIN DURING COMPARING THAT LAST SAW X IS IT STILL 42 IF X IS STILL 42 THEN CHANGE TO 50 ELSE DONT CHANGE AND *****RETRY*****(bcoz itne time me koi aur thread x ki value change krde)
        //RETRY -> COME BACK --> SAY ANOTHER THREAD MADE X = 45 SO LAST SAW VALUE ALSO CHANGED
        // SO IT CHECKS AGAIN THAT LAST SAW X IS IT STILL 45 IF X IS STILL 45 THEN CHANGE TO 50 ELSE DONT CHANGE AND ****RETRY****

        //RETRY CHALTA H LOCK NHI LAGTA BUT CONTINUOUS IT WONT RUN LIKE INFINITE LOOP BCOZ IF CAS FAIL BAR BAR THREAD CAN WAIT A BIT RUK JAIGA SHORT RANDOM TIME KE BADH RETRY
        // SO TO AVOID CPU WASTAGE COMPLEXITY TOO HIGH


        //HASHMAP EXAMPLE
        // PUT --> INDEX (BY HASHING) --> CHECK IF INDEX IS EMPTY AND WHEN WE R GOING TO PUT KEY VALUE PAIR CHECK AGAIN BY COMPARE & SWAP IF INDEX IS EMPTY
        // UPDATE --> WE WILL HAVE LAST SAW VALUE UPDATE KRTE TIME CHECK AGAIN IF LAST SAW VALUE SAME NOW ALSO THEN UPDATE OTW WAIT & RETRY

        //similarly if beyond a certain threshold key value pairs come in then size increases IN CONCURRENTHASHMAP
        // ****conventional hashmap and concurrentHashmap resizing is different****
        // HASHMAP -> INTERNAL ARRAY SIZE DOUBLES BEYOND THRESHOLD LOAD FACTOR = 0.75(16 (DEFAULT CAPACITY) *0.75 = 12) (CAPACITY*0.75 < NO OF VALUES )
        // CONCURRENTHASHMAP -> INTERNAL ARRAY SIZE DO NOT DOUBLE INCREMENTAL RESIZING, ONCE SIZE FULL ADD 1 MORE BUCKET MAYBE 2 THREADS COME AND TRY TO HOLD THAT SAME BUCKET THEN IN THAT CASE LOCK IS NECESSARY
        // HENCE LOCKING HAPPENS IN RESIZING AND COLLISION IN CONCURRENTHASHMAP
        // READ -> NO LOCKING
        // WRITE -> CAS APPROACH
    }
}
